<?php
define("ROOT",str_replace(DIRECTORY_SEPARATOR."public".DIRECTORY_SEPARATOR."index.php", "", $_SERVER["SCRIPT_FILENAME"]));
define("ROOT_CONFIG",ROOT.DIRECTORY_SEPARATOR."config".DIRECTORY_SEPARATOR);
define("ROOT_VIEWS",ROOT.DIRECTORY_SEPARATOR."views".DIRECTORY_SEPARATOR);
define("ROOT_VIEWS_INC",ROOT_VIEWS."inc".DIRECTORY_SEPARATOR);
define("ROOT_LIB",ROOT.DIRECTORY_SEPARATOR."lib".DIRECTORY_SEPARATOR);
define("ROOT_MODELS",ROOT.DIRECTORY_SEPARATOR."models".DIRECTORY_SEPARATOR);
define("ROOT_LAYOUT",ROOT_VIEWS."layout".DIRECTORY_SEPARATOR);
define("WEB_ROOT","http://localhost:8000/");
define("ROOT_CONTROLLERS",WEB_ROOT."controllers");
?>